server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.entity

# https://blog.csdn.net/sayyy/article/details/80843805
management:
  endpoints:
    web:
      exposure:
        include: "*"

#showSql
logging:
  level:
    org:
      py: debug
